/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

public interface ParserConstants {

    int SELECT = 5;
    int FROM = 6;
    int WHERE = 7;
    int AND = 8;
    int OPEN_PAR = 9;
    int CLOSE_PAR = 10;
    int DOT = 11;
    int COMMA = 12;
    int QUO = 13;
    int OPERATOR = 14;
    int DIGITS = 15;
    int NAME = 16;

    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\t\"",
            "\"\\r\"",
            "\"\\n\"",
            "\"SELECT\"",
            "\"FROM\"",
            "\"WHERE\"",
            "\"AND\"",
            "\"(\"",
            "\")\"",
            "\".\"",
            "\",\"",
            "\"\\\"\"",
            "<OPERATOR>",
            "<DIGITS>",
            "<NAME>",
    };

}
