/* Generated By:JavaCC: Do not edit this line. Token.java Version 5.0 */
/* JavaCCOptions:TOKEN_EXTENDS=,KEEP_LINE_COL=null,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

import java.io.Serial;

public class Token implements java.io.Serializable {
    @Serial
    private static final long serialVersionUID = 1L;
    public int kind;
    public int beginLine;
    public int beginColumn;
    public int endLine;
    public int endColumn;

    public String image;

    public Token next;
    public Token() {}

    public Token(int kind)
    {
        this(kind, null);
    }

    public Token(int kind, String image)
    {
        this.kind = kind;
        this.image = image;
    }

    public String toString()
    {
        return image;
    }

    public static Token newToken(int ofKind, String image)
    {
        return new Token(ofKind, image);
    }


}
/* JavaCC - OriginalChecksum=6145f5d5b504ccb4f95e09f2ce3e748a (do not edit this line) */
