import java.io.Serial;

/* Generated By:JavaCC: Do not edit this line. TokenMgrError.java Version 5.0 */
/* JavaCCOptions: */
public class TokenMgrError extends Error
{
    @Serial
    private static final long serialVersionUID = 1L;
    static final int LEXICAL_ERROR = 0;
    static final int STATIC_LEXER_ERROR = 1;
    static final int INVALID_LEXICAL_STATE = 2;

    int errorCode;
    protected static String addEscapes(String str) {
        StringBuilder retval = new StringBuilder();
        char ch;
        for (int i = 0; i < str.length(); i++) {
            switch (str.charAt(i)) {
                case 0 -> {
                }
                case '\b' -> {
                    retval.append("\\b");
                }
                case '\t' -> {
                    retval.append("\\t");
                }
                case '\n' -> {
                    retval.append("\\n");
                }
                case '\f' -> {
                    retval.append("\\f");
                }
                case '\r' -> {
                    retval.append("\\r");
                }
                case '\"' -> {
                    retval.append("\\\"");
                }
                case '\'' -> {
                    retval.append("\\\'");
                }
                case '\\' -> {
                    retval.append("\\\\");
                }
                default -> {
                    if ((ch = str.charAt(i)) < 0x20 || ch > 0x7e) {
                        String s = "0000" + Integer.toString(ch, 16);
                        retval.append("\\u").append(s.substring(s.length() - 4));
                    } else {
                        retval.append(ch);
                    }
                }
            }
        }
        return retval.toString();
    }
    protected static String LexicalError(boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar) {
        return("Lexical error at line " +
                errorLine + ", column " +
                errorColumn + ".  Encountered: " +
                (EOFSeen ? "<EOF> " : ("\"" + addEscapes(String.valueOf(curChar)) + "\"") + " (" + (int)curChar + "), ") +
                "after : \"" + addEscapes(errorAfter) + "\"");
    }

    public String getMessage() {
        return super.getMessage();
    }

    public TokenMgrError(String message, int reason) {
        super(message);
        errorCode = reason;
    }

    public TokenMgrError(boolean EOFSeen, int lexState, int errorLine, int errorColumn, String errorAfter, char curChar, int reason) {
        this(LexicalError(EOFSeen, lexState, errorLine, errorColumn, errorAfter, curChar), reason);
    }
}
/* JavaCC - OriginalChecksum=3f827858bf5c87e5502cccca67d9b325 (do not edit this line) */
